# Soal Hans on 2 - Aljabar Linear
Nama : Muhammad Ferianda Satya
Nim : 1301164400

In [30]:
#import numpy library
import numpy as np
import numpy.matlib

# Soal A

In [31]:
#M merupakan matriks 4x3 sehingga direpresentasikan menjadi array 2 dimensi
M = np.array([[1,2,3],[4,5,6],[7,8,9],[0,2,2]])
#a merupakan matriks 3x1 sehingga direpresentasikan menjadi array 2 dimensi
a = np.array([[1],[1],[0]])
#b merupakan matriks 3x1 sehingga direpresentasikan menjadi array 2 dimensi
b = np.array([[-1],[2],[5]])
#c merupakan matriks 4x1 sehingga direpresentasikan menjadi array 2 dimensi
c = np.array([[0],[2],[3],[2]])

# Soal B

In [32]:
aDotb = a @ b
# aDotb = np.dot(a,b) bentuk lain operasi dot product
print(aDotb)
# terjadi error karena syarat dot produk axb dengan bxc axc, atau kolom matriks pertama harus berjumlah sama dengan baris matriks kedua

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

# Soal C

In [33]:
aXb = a * b
# aXb = np.multiply(a,b) bentuk lain operasi element-wise product
print(aXb)

[[-1]
 [ 2]
 [ 0]]


# Soal D

In [34]:
# menghitung (aTb)Ma
d = (a.T @ b) * M @ a #tidak ada aturan menggunakan dot atau wise
print(d)

[[ 3]
 [ 9]
 [15]
 [ 2]]


# Soal E

In [62]:
i = np.matlib.repmat(M[0],1,len(a))
res = i * 

TypeError: only integer scalar arrays can be converted to a scalar index

In [60]:
M[0] * a

array([[1, 2, 3],
       [1, 2, 3],
       [0, 0, 0]])